

#ifndef MMCOP_PRE_CONTROLS
#define MMCOP_PRE_CONTROLS

// Function controls
#define MMCOP_DEFAULT_VERSION 1
#define MMCOP_DEFAULT_DO_MULTI_THREADED true

// Parameters
#define MMCOP_DEFAULT_TOTAL_RUNS 10'000
#define MMCOP_DEFAULT_TOTAL_TIMESTEPS 504
#define MMCOP_DEFAULT_SEED 1

#define MMCOP_DEFAULT_INITIAL_PRICE 100
#define MMCOP_DEFAULT_INITIAL_VARIANCE 0.04
#define MMCOP_DEFAULT_TIMESTEP ( 1.0 / 252.0 )
#define MMCOP_DEFAULT_DRIFT 0.04
#define MMCOP_DEFAULT_MEAN_REVERSION_SPEED 1.2
#define MMCOP_DEFAULT_MEAN_REVERSION_LEVEL 0.05
#define MMCOP_DEFAULT_VOLATILITY 0.3
#define MMCOP_DEFAULT_CORRELATION_FACTOR -0.6

#define MMCOP_DEFAULT_STRIKE_PRICE 100
#define MMCOP_DEFAULT_DISCOUNTING_RATE 0.95

#define MMCOP_GPU_DEFAULT_CONCURRENT_RUNS 1024


// File Related
#define MMCOP_OUTPUT_DIRECTORY_PREFIX "mmcop_output"
#define MMCOP_OUTPUT_FILE_PREFIX "all_paths_output"


// OpenMP related
#define MMCOP_THREAD_SEED_MAGIC_NUMBER 2
#define MMCOP_NUMBER_OF_THREADS 4


// MPI Related
#define MMCOP_RANK_SEED_MAGIC_NUMBER 137
#define MMCOP_USE_MPI 1

#endif
